apiVersion: v1
kind: Service
metadata:
  name: valaxy-service
  labels:
    app: regapp 
spec:
  selector:
    app: regapp 

  ports:
    - port: 8080
      targetPort: 8080

  type: LoadBalancer


---
TASK [lablabs.rke2 : Run RKE2 install script with airgap variables] ***********************************************************************
fatal: [master01]: FAILED! => {"changed": false, "cmd": "/var/tmp/rke2.sh", "msg": "[Errno 2] No such file or directory: b'/var/tmp/rke2.sh                              '", "rc": 2, "stderr": "", "stderr_lines": [], "stdout": "", "stdout_lines": []}

PLAY RECAP ********************************************************************************************************************************
master01                   : ok=12   changed=3    unreachable=0    failed=1    skipped=14   rescued=0    ignored=0

ooridota@ca-gat-dc1-nosd-stg-vm-jmp-01:~/nonprd$

